[package]
name = "j3sg-gen"
version = "0.2.0"
edition = "2021"

[dependencies]
log = "0.4.20"
markdown = "1.0.0-alpha.12"
serde = { version="1.0", features=["derive"] }
serde_yaml = "0.9.25"
tera = "1.19.1"
